DROP TABLE IF EXISTS user_credentials;
--DROP TABLE IF EXISTS user_profiles

DROP TABLE IF EXISTS user_credentials;

CREATE TABLE user_credentials
(
  id BIGINT NOT NULL AUTO_INCREMENT,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (email)
-- Deberia agregar updated_at
);



--CREATE TABLE user_profiles
--(
--    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   name VARCHAR(100) NOT NULL,
--    surname VARCHAR(100) NOT NULL,
--    birthdate DATE NOT NULL,
--    dni VARCHAR(9) NOT NULL UNIQUE, -- Agregar limite de solo numeros
--    is_enabled BOOLEAN NOT NULL DEFAULT FALSE,
--    role ENUM("PATIENT", "DOCTOR","ADMINISTRATOR")
--)

    --	id
    --	credential_id
    --	name
    --	surname
    --	birthdate
    --	dni
    --	email
    --	is_enabled
    --	role (PATIENT, DOCTOR, ADMINISTRATOR)
    --	profile_img_url
    --	created_at
    --	updated_at