DROP TABLE IF EXISTS user_credentials;
DROP TABLE IF EXISTS user_profiles;

CREATE TABLE user_credentials
(
  id BIGINT NOT NULL AUTO_INCREMENT,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (email)
);

CREATE TABLE user_profiles
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credential_id BIGINT UNIQUE,
    name VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    birthdate DATE NOT NULL,
    dni VARCHAR(9) NOT NULL UNIQUE,
    is_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    role ENUM("PATIENT", "DOCTOR","ADMIN") NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(credential_id) REFERENCES user_credentials(id),
    CHECK(dni REGEXP '^[0-9]{1,9}$')
);

    --	id
    --	credential_id
    --	name
    --	surname
    --	birthdate
    --	dni
    --	email
    --	is_enabled
    --	role (PATIENT, DOCTOR, ADMINISTRATOR)
    --	profile_img_url
    --	created_at
    --	updated_at